### ISSUE TITLE
Refactor how we store notifications subscription information

### ISSUE THREAD

**Issue by padovan** [kernelci/dashboard#1206]
Today we store the recipients per tree at the `recipients.yaml` file. Then we \[have\] the `summary-signup.yaml` file for people. We have to combine it all in a single file per tree. So let's create the folder `backend/data/subscriptions` and add a file for each \[tree\] there following the yaml format below: 

```
tree:
  url: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
  default_recipients:
    - laura.nao@collabora.com
    - shreeya.patel@collabora.com
    - broonie@kernel.org
 
  reports:
    - default:
      origin: maestro
      branch: master

    - rt_tests:
      origin: maestro
      branch: master
      path:
        - rt-tests*
      recipients:
        - linux-rt-devel@lists.linux.dev
      options:
        - ignore_default_recipients
```

`default_recipients`  has the email address that will receive issues reports and default status summary.

`reports:` section are to list the different summary reports users may want to have.
